# Generated by Django 4.0.4 on 2022-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='user',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='emp_address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='emp_name',
            field=models.CharField(default=11, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='empid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
