# Generated by Django 4.0.4 on 2022-05-24 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0002_remove_doctormodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='emp_address',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='empid',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='address',
            field=models.CharField(default=10, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
