# Generated by Django 4.0.4 on 2022-05-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0005_rename_profile_pic_doctormodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.docter_dep'),
        ),
    ]
