# Generated by Django 4.0.4 on 2022-05-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0009_alter_doctormodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='qualification',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
