# Generated by Django 4.0.4 on 2022-05-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0013_appoinmentmodel_date_alter_docter_dep_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
