# Generated by Django 4.0.4 on 2022-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0018_alter_paymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodel',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
