# Generated by Django 4.0.4 on 2022-05-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0019_alter_paymodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymodel',
            name='user',
        ),
        migrations.AddField(
            model_name='paymodel',
            name='doc_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Master.doctormodel'),
            preserve_default=False,
        ),
    ]
