# Generated by Django 4.0.4 on 2022-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0022_remove_paymodel_doc_paymodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=560)),
            ],
        ),
    ]
