# Generated by Django 4.0.4 on 2022-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0023_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
